"use strict";

window.ZIWEI_TEACHING_DATA = {
  schemaVersion: 1,
  source: {
    bookTitle: "安星法及推斷實例",
    priority: "EPUB 原文優先，Markdown 摘要僅作索引與輔助"
  },
  lessons: [
    {
      id: "load-input",
      order: 1,
      title: "載入出生資料",
      shortTitle: "出生資料",
      type: "normalize-input",
      prerequisiteStepIds: [],
      ruleIds: ["normalize-input"],
      status: "verified",
      narration: ["讀取性別、年干支、農曆月日、時辰與時間校正欄位。"],
      commonMistakes: ["未區分手動陰曆與陽曆換算模式。"]
    },
    {
      id: "effective-lunar-month",
      order: 2,
      title: "閏月月份歸屬判定",
      shortTitle: "閏月",
      type: "calculate",
      prerequisiteStepIds: ["load-input"],
      ruleIds: ["normalize-input"],
      status: "verified",
      narration: ["判斷閏月前半照前月，後半作下月。"],
      commonMistakes: ["把閏月整月當成本月。"]
    },
    {
      id: "yin-yang-gender",
      order: 3,
      title: "判定年干陰陽與陰陽男女",
      shortTitle: "陰陽男女",
      type: "calculate",
      prerequisiteStepIds: ["effective-lunar-month"],
      ruleIds: ["major-limit"],
      status: "verified",
      narration: ["以年干陰陽與性別決定陽男、陰男、陽女、陰女。"],
      commonMistakes: ["只看性別，不看年干陰陽。"]
    },
    {
      id: "build-palaces",
      order: 4,
      title: "建立十二地支座標",
      shortTitle: "地支座標",
      type: "place-palace",
      prerequisiteStepIds: ["yin-yang-gender"],
      ruleIds: ["place-ming"],
      status: "verified",
      narration: ["先固定十二地支座標；此步只建立盤面位置，尚未安命宮、人事十二宮與星曜。"],
      commonMistakes: ["方盤顯示順序與內部地支順序混用。"]
    },
    {
      id: "place-ming",
      order: 5,
      title: "安命宮",
      shortTitle: "命宮",
      type: "place-palace",
      prerequisiteStepIds: ["build-palaces"],
      ruleIds: ["place-ming"],
      status: "verified",
      narration: ["寅起正月順至生月，再從生月宮起子時逆數至生時。"],
      commonMistakes: ["把命宮順數，或起點未算第一步。"]
    },
    {
      id: "place-shen",
      order: 6,
      title: "安身宮",
      shortTitle: "身宮",
      type: "place-palace",
      prerequisiteStepIds: ["place-ming"],
      ruleIds: ["place-shen"],
      status: "verified",
      narration: ["身宮同樣從生月宮起子時，但順數至生時。"],
      commonMistakes: ["把身宮也逆數。"]
    },
    {
      id: "name-palaces",
      order: 7,
      title: "逆布十二人事宮",
      shortTitle: "十二宮名",
      type: "place-palace",
      prerequisiteStepIds: ["place-shen"],
      ruleIds: ["name-palaces"],
      status: "verified",
      narration: ["命宮定位後，由命宮起命，逆行依序布兄弟、夫妻、子女、財帛、疾厄、遷移、僕役、官祿、田宅、福德、父母。"],
      commonMistakes: ["命宮一定先定；十二人事宮名由命宮逆布，不是從寅宮固定起布。"]
    },
    {
      id: "palace-stems",
      order: 8,
      title: "五虎遁安十二宮天干",
      shortTitle: "宮干",
      type: "calculate",
      prerequisiteStepIds: ["place-shen"],
      ruleIds: ["palace-stems"],
      status: "verified",
      narration: ["依五虎遁：甲己之年丙作首，乙庚之歲戊為頭，丙辛必定尋庚起，丁壬壬位順行流，若問戊癸何方發，甲寅之上好追求。由寅宮起干，順布十二宮。"],
      commonMistakes: ["直接用出生年干當命宮干。"]
    },
    {
      id: "determine-bureau",
      order: 9,
      title: "定五行局",
      shortTitle: "五行局",
      type: "calculate",
      prerequisiteStepIds: ["palace-stems"],
      ruleIds: ["determine-bureau"],
      status: "verified",
      purpose: "以命宮干支查六十納音，定五行後轉為水二、木三、金四、土五、火六局。",
      narration: ["六十納音訣：甲乙錦江煙，丙丁沒谷田，戊己營堤柳（子寅辰、午申戌）；庚辛掛杖錢，壬癸林鐘滿，花甲納音全（丑卯巳、未酉亥）。"],
      commonMistakes: ["用年柱納音定局，而非命宮干支。"]
    },
    {
      id: "major-limit",
      order: 10,
      title: "起大限",
      shortTitle: "大限",
      type: "calculate",
      prerequisiteStepIds: ["determine-bureau"],
      ruleIds: ["major-limit"],
      status: "verified",
      narration: ["以局數為第一大限起歲，再依陽男陰女順、陰男陽女逆布大限。"],
      commonMistakes: ["大限方向與博士十二神方向混用。"]
    },
    {
      id: "small-limit",
      order: 11,
      title: "起小限",
      shortTitle: "小限",
      type: "calculate",
      prerequisiteStepIds: ["major-limit"],
      ruleIds: ["small-limit"],
      status: "verified",
      purpose: "依出生年支定小限一歲起宮，再依性別順逆布每年小限。",
      narration: ["小限以出生年支定一歲起宮，男順女逆，逐歲輪十二宮。"],
      commonMistakes: ["小限不是大限；小限逐年輪宮，盤面只列本宮對應歲數摘要。"]
    },
    {
      id: "place-ziwei",
      order: 11,
      title: "安紫微星",
      shortTitle: "紫微",
      type: "place-star",
      prerequisiteStepIds: ["small-limit"],
      ruleIds: ["place-ziwei"],
      status: "needs_review",
      narration: ["以出生日除以五行局數，依整除、有餘數、日數小於局數三分支定位。"],
      commonMistakes: ["未說明餘數宮表來源，或把補數法與原書除法混用。"]
    },
    {
      id: "place-tianji",
      order: 12,
      title: "安天機",
      shortTitle: "天機",
      type: "place-star",
      prerequisiteStepIds: ["place-ziwei"],
      ruleIds: ["place-tianji"],
      status: "verified",
      narration: ["紫微逆去宿天機。"],
      commonMistakes: ["忘記紫微系由紫微宮逆布。"]
    },
    {
      id: "place-taiyang",
      order: 13,
      title: "安太陽",
      shortTitle: "太陽",
      type: "place-star",
      prerequisiteStepIds: ["place-tianji"],
      ruleIds: ["place-taiyang"],
      status: "verified",
      narration: ["隔一太陽武曲移。"],
      commonMistakes: ["把太陽安在天機下一宮，少隔一宮。"]
    },
    {
      id: "place-wuqu",
      order: 14,
      title: "安武曲",
      shortTitle: "武曲",
      type: "place-star",
      prerequisiteStepIds: ["place-taiyang"],
      ruleIds: ["place-wuqu"],
      status: "verified",
      narration: ["太陽後續安武曲。"],
      commonMistakes: ["未按紫微系固定偏移。"]
    },
    {
      id: "place-tiantong",
      order: 15,
      title: "安天同",
      shortTitle: "天同",
      type: "place-star",
      prerequisiteStepIds: ["place-wuqu"],
      ruleIds: ["place-tong"],
      status: "verified",
      narration: ["天同隔二廉貞位。"],
      commonMistakes: ["天同、廉貞間隔數錯。"]
    },
    {
      id: "place-lianzhen",
      order: 16,
      title: "安廉貞",
      shortTitle: "廉貞",
      type: "place-star",
      prerequisiteStepIds: ["place-tiantong"],
      ruleIds: ["place-lianzhen"],
      status: "verified",
      narration: ["紫微系最後安廉貞。"],
      commonMistakes: ["把廉貞接在天同下一宮。"]
    },
    {
      id: "place-tianfu",
      order: 17,
      title: "依紫微安天府",
      shortTitle: "天府",
      type: "place-star",
      prerequisiteStepIds: ["place-lianzhen"],
      ruleIds: ["place-tianfu"],
      status: "verified",
      narration: ["依紫微與天府相對聚散表定位天府。"],
      commonMistakes: ["把天府系順布起點弄成紫微宮。"]
    },
    {
      id: "place-taiyin",
      order: 18,
      title: "安太陰",
      shortTitle: "太陰",
      type: "place-star",
      prerequisiteStepIds: ["place-tianfu"],
      ruleIds: ["place-taiyin"],
      status: "verified",
      narration: ["天府系由天府順布太陰。"],
      commonMistakes: ["天府系方向與紫微系混淆。"]
    },
    {
      id: "place-tanlang",
      order: 19,
      title: "安貪狼",
      shortTitle: "貪狼",
      type: "place-star",
      prerequisiteStepIds: ["place-taiyin"],
      ruleIds: ["place-tanlang"],
      status: "verified",
      narration: ["由天府順布至貪狼。"],
      commonMistakes: ["漏算太陰。"]
    },
    {
      id: "place-jumen",
      order: 20,
      title: "安巨門",
      shortTitle: "巨門",
      type: "place-star",
      prerequisiteStepIds: ["place-tanlang"],
      ruleIds: ["place-jumen"],
      status: "verified",
      narration: ["由天府系順布至巨門。"],
      commonMistakes: ["天府系星序錯置。"]
    },
    {
      id: "place-tianxiang",
      order: 21,
      title: "安天相",
      shortTitle: "天相",
      type: "place-star",
      prerequisiteStepIds: ["place-jumen"],
      ruleIds: ["place-tianxiang"],
      status: "verified",
      narration: ["由天府系順布至天相。"],
      commonMistakes: ["天相與天梁順序顛倒。"]
    },
    {
      id: "place-tianliang",
      order: 22,
      title: "安天梁",
      shortTitle: "天梁",
      type: "place-star",
      prerequisiteStepIds: ["place-tianxiang"],
      ruleIds: ["place-tianliang"],
      status: "verified",
      narration: ["由天府系順布至天梁。"],
      commonMistakes: ["天梁偏移錯。"]
    },
    {
      id: "place-qisha",
      order: 23,
      title: "安七殺",
      shortTitle: "七殺",
      type: "place-star",
      prerequisiteStepIds: ["place-tianliang"],
      ruleIds: ["place-qisha"],
      status: "verified",
      narration: ["由天府系順布至七殺。"],
      commonMistakes: ["七殺與破軍規則混用。"]
    },
    {
      id: "place-pojun",
      order: 24,
      title: "安破軍",
      shortTitle: "破軍",
      type: "place-star",
      prerequisiteStepIds: ["place-qisha"],
      ruleIds: ["place-pojun"],
      status: "verified",
      narration: ["七殺空三是破軍。由七殺宮空三宮，再安破軍。"],
      commonMistakes: ["破軍不是接在七殺下一宮。"]
    },
    {
      id: "place-zuofu",
      order: 25,
      title: "安左輔",
      shortTitle: "左輔",
      type: "place-star",
      prerequisiteStepIds: ["place-pojun"],
      ruleIds: ["place-zuofu"],
      status: "verified",
      narration: ["辰上順正尋左輔。由辰宮起正月，順數至生月安左輔。"],
      commonMistakes: ["把左輔誤從戌宮起，或忘記以有效農曆月計。"]
    },
    {
      id: "place-youbi",
      order: 26,
      title: "安右弼",
      shortTitle: "右弼",
      type: "place-star",
      prerequisiteStepIds: ["place-zuofu"],
      ruleIds: ["place-youbi"],
      status: "verified",
      narration: ["戌上逆正右弼當。由戌宮起正月，逆數至生月安右弼。"],
      commonMistakes: ["右弼方向應逆行。"]
    },
    {
      id: "place-wenqu",
      order: 27,
      title: "安文曲",
      shortTitle: "文曲",
      type: "place-star",
      prerequisiteStepIds: ["place-youbi"],
      ruleIds: ["place-wenqu"],
      status: "verified",
      narration: ["辰上順時文曲位。由辰宮起子時，順數至生時安文曲。"],
      commonMistakes: ["文曲從辰起順行，不是從戌起。"]
    },
    {
      id: "place-wenchang",
      order: 28,
      title: "安文昌",
      shortTitle: "文昌",
      type: "place-star",
      prerequisiteStepIds: ["place-wenqu"],
      ruleIds: ["place-wenchang"],
      status: "verified",
      narration: ["戌上逆時覓文昌。由戌宮起子時，逆數至生時安文昌。"],
      commonMistakes: ["文昌從戌起逆行，不是與文曲同向。"]
    },
    {
      id: "place-dijie",
      order: 29,
      title: "安地劫",
      shortTitle: "地劫",
      type: "place-star",
      prerequisiteStepIds: ["place-wenchang"],
      ruleIds: ["place-dijie"],
      status: "verified",
      narration: ["亥上子時順安劫。由亥宮起子時，順數至生時安地劫。"],
      commonMistakes: ["地劫順行，地空逆行。"]
    },
    {
      id: "place-dikong",
      order: 30,
      title: "安地空",
      shortTitle: "地空",
      type: "place-star",
      prerequisiteStepIds: ["place-dijie"],
      ruleIds: ["place-dikong"],
      status: "verified",
      narration: ["逆回便是地空亡。由亥宮起子時，逆數至生時安地空。"],
      commonMistakes: ["地空不是地劫對宮，需由亥逆數。"]
    },
    {
      id: "four-transformations",
      order: 31,
      title: "安生年四化",
      shortTitle: "四化",
      type: "transform-star",
      prerequisiteStepIds: ["place-dikong"],
      ruleIds: ["four-transformations"],
      status: "verified",
      purpose: "依生年天干查四化，按祿、權、科、忌順序附著到原星。",
      narration: ["甲廉破武陽，乙機梁紫陰；丙同機昌廉，丁陰同機巨；戊貪陰陽機，己武貪梁曲；庚陽武府同，辛巨陽曲昌；壬梁紫府武，癸破巨陰貪。"],
      commonMistakes: ["把四化當成單獨星曜放入宮位。"]
    },
    {
      id: "place-kui-yue",
      order: 32,
      title: "安天魁天鉞",
      shortTitle: "魁鉞",
      type: "place-star",
      prerequisiteStepIds: ["four-transformations"],
      ruleIds: ["place-kui", "place-yue"],
      status: "verified",
      narration: ["甲戊庚牛羊，乙己鼠猴鄉，丙丁豬雞位，壬癸兔蛇藏，六辛逢馬虎，魁鉞貴人方。每組前字為天魁，後字為天鉞；辛干為馬午安魁、虎寅安鉞。"],
      commonMistakes: ["口訣兩字順序不可倒；六辛逢馬虎是魁在午、鉞在寅。"]
    },
    {
      id: "place-lucun-yang-tuo",
      order: 33,
      title: "安祿存擎羊陀羅",
      shortTitle: "祿羊陀",
      type: "place-star",
      prerequisiteStepIds: ["place-kui-yue"],
      ruleIds: ["place-lucun", "place-qingyang", "place-tuoluo"],
      status: "verified",
      narration: ["甲祿到寅宮，乙祿居卯府，丙戊祿在巳，丁己祿在午，庚祿定居申，辛祿酉上補，壬祿亥中藏，癸祿居子戶，祿前擎羊當，祿後陀羅府。"],
      commonMistakes: ["先定祿存，再以前一宮安擎羊、後一宮安陀羅。"]
    },
    {
      id: "place-fire-bell",
      order: 34,
      title: "安火鈴",
      shortTitle: "火鈴",
      type: "place-star",
      prerequisiteStepIds: ["place-lucun-yang-tuo"],
      ruleIds: ["place-fire", "place-bell"],
      status: "verified",
      narration: ["申子辰人寅戌揚，寅午戌人丑卯方，巳酉丑人卯戌位，亥卯未人酉戌房。先據年支定火星、鈴星子時起位，再順數至生時。"],
      commonMistakes: ["火鈴起點是兩個宮位，且都順數至生時。"]
    },
    {
      id: "place-tian-guan-fu",
      order: 35,
      title: "安天官天福",
      shortTitle: "官福",
      type: "place-star",
      prerequisiteStepIds: ["place-fire-bell"],
      ruleIds: ["place-tianguan", "place-tianfu-minor"],
      status: "verified",
      narration: ["甲喜羊雞乙龍猴，丙年蛇鼠一窩謀，丁虎擒豬戊玉兔，己雞居然與虎儔，庚豬馬辛雞蛇走，壬犬馬癸馬蛇游。每句前者天官，後者天福。"],
      commonMistakes: ["天福雖同名，不可與十四正曜天府混淆。"]
    },
    {
      id: "place-tianchu",
      order: 36,
      title: "安天廚",
      shortTitle: "天廚",
      type: "place-star",
      prerequisiteStepIds: ["place-tian-guan-fu"],
      ruleIds: ["place-tianchu"],
      status: "verified",
      narration: ["甲丁食蛇口，乙戊辛馬方，丙從鼠口得，己食於猴房，庚食虎頭上，壬雞癸豬堂。依年干查宮安天廚。"],
      commonMistakes: ["天廚依年干，不依年支。"]
    },
    {
      id: "place-jiekong",
      order: 37,
      title: "安截空",
      shortTitle: "截空",
      type: "place-star",
      prerequisiteStepIds: ["place-tianchu"],
      ruleIds: ["place-jiekong"],
      status: "verified",
      narration: ["戊癸子丑起，推至甲己止，申酉是截空，戌亥不論此。截空占二宮，依年干陰陽分正空、傍空。"],
      commonMistakes: ["截空不入戌亥；需分正空傍空。"]
    },
    {
      id: "place-xunkong",
      order: 38,
      title: "安旬空",
      shortTitle: "旬空",
      type: "place-star",
      prerequisiteStepIds: ["place-jiekong"],
      ruleIds: ["place-xunkong"],
      status: "verified",
      narration: ["依年干年支順數至癸後二位。天干數至癸止，其後二宮即旬空，亦分正空、傍空。"],
      commonMistakes: ["旬空用年干年支推旬，不是固定查年支。"]
    },
    {
      id: "place-tianma-tiankong",
      order: 39,
      title: "安天馬天空",
      shortTitle: "馬空",
      type: "place-star",
      prerequisiteStepIds: ["place-xunkong"],
      ruleIds: ["place-tianma", "place-tiankong"],
      status: "verified",
      narration: ["駕前一位是天空，身命原來不可逢。寅申巳亥天馬位，三合長生恰對沖。天空在年支前一宮；天馬以年支三合局長生之沖宮安星。"],
      commonMistakes: ["天空與地空不同；天馬看年支三合局。"]
    },
    {
      id: "place-cry-void",
      order: 40,
      title: "安天哭天虛",
      shortTitle: "哭虛",
      type: "place-star",
      prerequisiteStepIds: ["place-tianma-tiankong"],
      ruleIds: ["place-tianku", "place-tianxu"],
      status: "verified",
      narration: ["天哭天虛起午宮，午宮起子兩分蹤，哭逆巳兮虛順未，生年尋到便居中。天哭由午起子逆數至年支；天虛由午起子順數至年支。"],
      commonMistakes: ["哭逆虛順不可顛倒。"]
    },
    {
      id: "place-red-happy",
      order: 41,
      title: "安紅鸞天喜",
      shortTitle: "紅喜",
      type: "place-star",
      prerequisiteStepIds: ["place-cry-void"],
      ruleIds: ["place-hongluan", "place-tianxi"],
      status: "verified",
      narration: ["卯上子年逆數之，數到當生太歲支，坐守此宮紅鸞位，對宮天喜不差移。紅鸞由卯起子逆數至年支；天喜在紅鸞對宮。"],
      commonMistakes: ["天喜直接取紅鸞對宮。"]
    },
    {
      id: "place-lonely-widow",
      order: 42,
      title: "安孤辰寡宿",
      shortTitle: "孤寡",
      type: "place-star",
      prerequisiteStepIds: ["place-red-happy"],
      ruleIds: ["place-guchen", "place-guasuo"],
      status: "verified",
      narration: ["寅卯辰方安巳丑，巳午未方怕申辰，申酉戌方屬亥未，亥子丑方寅戌嗔。每組前者孤辰，後者寡宿。"],
      commonMistakes: ["按年支方局查，不按單一年支逐宮數。"]
    },
    ...[
      ["place-jiesha", "安劫煞", "劫煞", "申子辰人蛇開口，亥卯未人猴速走，寅午戌人豬面黑，巳酉丑人虎咆哮。", "依年支三合局取絕位安劫煞。"],
      ["place-dahao", "安大耗", "大耗", "但用年支去對沖，陰陽移位過一宮，陽順陰逆移其位，大耗原來不可逢。", "依年支對宮，再按陽支順、陰支逆移一宮安大耗。"],
      ["place-feilian", "安蜚廉", "蜚廉", "子丑寅年生人，蜚廉在申酉戌；卯辰巳年生人，蜚廉在巳午未；午未申年生人，蜚廉在寅卯辰；酉戌亥年生人，蜚廉在亥子丑。", "依出生年支查四組對照表，同組內按年支順序對應宮位。"],
      ["place-posui", "安破碎", "破碎", "子午卯酉年在巳宮；寅申巳亥年在酉宮；辰戌丑未年在丑宮。", "依出生年支所屬三組直接查宮位。"],
      ["place-huagai", "安華蓋", "華蓋", "辰丑戌未輪華蓋。華蓋子年由辰宮起，按辰丑戌未輪排十二支。", "依年支按辰丑戌未輪排安華蓋。"],
      ["place-xianchi", "安咸池", "咸池", "酉午卯子布咸池。咸池由酉宮起，按酉午卯子輪排十二支。", "依年支按酉午卯子輪排安咸池。"],
      ["place-longde", "安龍德", "龍德", "龍德起羊。龍德由未宮起子年，順輪十二年支。", "由未宮起子年順數至年支安龍德。"],
      ["place-yuede", "安月德", "月德", "月起巳。月德由巳宮起子年，順輪十二年支。", "由巳宮起子年順數至年支安月德。"],
      ["place-tiande", "安天德", "天德", "天德星君起酉宮，順至生年定其蹤。", "由酉宮起子年順數至年支安天德。"],
      ["place-nianjie", "安年解", "年解", "年解戌宮逆行去，數至生年可解凶。", "由戌宮起子年逆數至年支安年解。"],
      ["place-tiancai", "安天才", "天才", "命宮起子天才順。", "由命宮起子年順數至年支安天才。"],
      ["place-tianshou", "安天壽", "天壽", "身宮起子天壽堂。", "由身宮起子年順數至年支安天壽。"]
    ].map(([id, title, shortTitle, narration, purpose], index) => ({
      id,
      order: 43 + index,
      title,
      shortTitle,
      type: "reference-table",
      prerequisiteStepIds: [index === 0 ? "place-lonely-widow" : [
        "place-jiesha", "place-dahao", "place-feilian", "place-posui", "place-huagai", "place-xianchi", "place-longde", "place-yuede", "place-tiande", "place-nianjie", "place-tiancai"
      ][index - 1]],
      ruleIds: [id],
      status: index < 12 ? "verified" : "needs_core",
      purpose,
      narration: [narration],
      commonMistakes: [index < 12 ? "依年支索引或子年起點順逆數，不可按方盤顯示位置數格。" : "已列書中口訣，尚未接入排盤核心。"]
    })),
    {
      id: "place-dragon-phoenix",
      order: 55,
      title: "安龍池鳳閣",
      shortTitle: "龍鳳",
      type: "place-star",
      prerequisiteStepIds: ["place-tianshou"],
      ruleIds: ["place-longchi", "place-fengge"],
      status: "verified",
      narration: ["龍池辰上子順行，生年到處福元真。鳳閣戌宮逆起子，遇到生年是此神。"],
      commonMistakes: ["龍池順行，鳳閣逆行。"]
    },
    ...[
      ["place-taifu", "安台輔", "台輔", "曲前二位是台輔。", "由文曲前二位安台輔。"],
      ["place-fenggao", "安封誥", "封誥", "曲後二位封誥鄉。", "由文曲後二位安封誥。"]
    ].map(([id, title, shortTitle, narration, purpose], index) => ({
      id,
      order: 56 + index,
      title,
      shortTitle,
      type: "reference-table",
      prerequisiteStepIds: [index === 0 ? "place-dragon-phoenix" : "place-taifu"],
      ruleIds: [id],
      status: "verified",
      purpose,
      narration: [narration],
      commonMistakes: ["此步依文曲位置，不直接依生時重數。"]
    })),
    {
      id: "place-tianxing",
      order: 58,
      title: "安天刑",
      shortTitle: "天刑",
      type: "place-star",
      prerequisiteStepIds: ["place-fenggao"],
      ruleIds: ["place-tianxing"],
      status: "verified",
      narration: ["天姚丑上順正月，天刑酉上正月輪，數至生月便住腳。現核心已接天刑：酉上起正月順數至有效生月。"],
      commonMistakes: ["天刑起酉，天姚起丑。"]
    },
    ...[
      ["place-tianyao", "安天姚", "天姚", "天姚丑上順正月。", "由丑宮起正月順數至有效生月安天姚。", "place-tianxing"],
      ["place-jieshen", "安解神", "解神", "單月沖宮覓解神，雙月還依單月辰。", "按兩個月同宮取月解，正二月同在寅宮對宮申。", "place-tianyao"],
      ["place-tianwu", "安天巫", "天巫", "巳申寅亥天巫位，分輪十二月星君。", "由巳申寅亥四宮分輪十二月安天巫。", "place-tianyao"],
      ["place-tianyue-minor", "安天月", "天月", "一犬二蛇三在龍，四虎五羊六兔宮，七豬八羊九在虎，十馬冬犬臘寅中。", "依有效農曆月查天月所在宮。", "place-tianwu"],
      ["place-yinsha", "安陰煞", "陰煞", "寅子戌，申午辰，分六月，陰煞臨。", "正月由寅起，隔一宮逆行輪排十二月安陰煞。", "place-tianyue-minor"]
    ].map(([id, title, shortTitle, narration, purpose, prerequisiteStepId], index) => ({
      id,
      order: 59 + index,
      title,
      shortTitle,
      type: "reference-table",
      prerequisiteStepIds: [prerequisiteStepId],
      ruleIds: [id],
      status: ["place-tianyao", "place-jieshen", "place-tianwu", "place-tianyue-minor", "place-yinsha"].includes(id) ? "verified" : "needs_core",
      purpose,
      narration: [narration],
      commonMistakes: ["月系雜曜需用有效農曆月，閏月應先處理。"]
    })),
    {
      id: "place-tianshang-tianshi",
      order: 64,
      title: "安天傷天使",
      shortTitle: "傷使",
      type: "place-star",
      prerequisiteStepIds: ["place-yinsha"],
      ruleIds: ["place-tianshang", "place-tianshi"],
      status: "verified",
      narration: ["天傷奴僕，天使疾厄，夾遷移宮，最易尋得。陽男陰女依此；陰男陽女則天傷居疾厄、天使居奴僕。"],
      commonMistakes: ["傷使依陰陽男女換位，不只看性別。"]
    },
    ...[
      ["place-santai", "安三台", "三台", "三台左輔起初一，數至生日是台宮。", "由左輔宮起初一，順數至生日安三台。", "place-tianshang-tianshi"],
      ["place-bazuo", "安八座", "八座", "八座右弼逆初一，數至生日定其蹤。", "由右弼宮起初一，逆數至生日安八座。", "place-santai"],
      ["place-enguang", "安恩光", "恩光", "文昌順數至生日，退後一步是恩光。", "由文昌宮起初一順數至生日，再退後一步安恩光。", "place-bazuo"],
      ["place-tiangui", "安天貴", "天貴", "文曲順數至生日，退後一步天貴方。", "由文曲宮起初一順數至生日，再退後一步安天貴。", "place-enguang"],
      ["place-mingzhu", "安命主", "命主", "子屬貪狼丑亥門，寅戌生人屬祿存，卯酉屬文巳未武，辰申廉宿午破軍。", "依年支查命主星。", "place-tiangui"],
      ["place-shenzhu", "安身主", "身主", "子午安身鈴火宿，丑未天相寅申梁，卯酉天同身主是，巳亥天機辰戌昌。", "依年支查身主星。", "place-mingzhu"]
    ].map(([id, title, shortTitle, narration, purpose, prerequisiteStepId], index) => ({
      id,
      order: 65 + index,
      title,
      shortTitle,
      type: "reference-table",
      prerequisiteStepIds: [prerequisiteStepId],
      ruleIds: [id],
      status: ["place-santai", "place-bazuo", "place-enguang", "place-tiangui", "place-mingzhu", "place-shenzhu"].includes(id) ? "verified" : "needs_core",
      purpose,
      narration: [narration],
      commonMistakes: [id === "place-mingzhu" || id === "place-shenzhu" ? "命主、身主是依年支定出的命盤屬性，不是另落一顆星到宮位。" : "此步依基準星與生日推算，不可改用生月或年支。"]
    })),
    {
      id: "place-changsheng",
      order: 71,
      title: "安長生十二神",
      shortTitle: "長生",
      type: "place-star",
      prerequisiteStepIds: ["place-shenzhu"],
      ruleIds: ["place-changsheng"],
      status: "verified",
      narration: ["金生巳，木生亥，火生寅，水土生申。依五行局起長生，陽男陰女順行，陰男陽女逆行。順序：長生、沐浴、冠帶、臨官、帝旺、衰、病、死、墓、絕、胎、養。"],
      commonMistakes: ["長生方向依陰陽男女，不只依五行局。"]
    },
    ...[
      "博士", "力士", "青龍", "小耗", "將軍", "奏書", "飛廉", "喜神", "病符", "大耗", "伏兵", "官符"
    ].map((starName, index) => ({
      id: `place-doctor-${index + 1}`,
      order: 72 + index,
      title: `安${starName}`,
      shortTitle: starName,
      type: "place-star",
      prerequisiteStepIds: [index === 0 ? "place-changsheng" : `place-doctor-${index}`],
      ruleIds: [`place-doctor-${starName}`],
      status: "verified",
      purpose: `依博士十二神順序安${starName}。`,
      narration: ["以出生年干定祿存起，分順逆。博士聰明力士權，青龍喜氣小耗錢，將軍威武奏書福，飛廉口舌喜神延，病符大耗皆非吉，伏兵官府相勾纏。博士起祿存，依陽男陰女順、陰男陽女逆布十二神。"],
      commonMistakes: ["博士十二神從祿存起，方向同大限順逆；同名星需看 category，不可與歲前十二神混用。"]
    })),
    ...[
      "歲建", "晦氣", "喪門", "貫索", "官符", "小耗", "大耗", "龍德", "白虎", "天德", "弔客", "病符"
    ].map((starName, index) => ({
      id: `place-suiqian-${index + 1}`,
      order: 84 + index,
      title: `安${starName}`,
      shortTitle: starName,
      type: "reference-table",
      prerequisiteStepIds: [index === 0 ? "place-doctor-12" : `place-suiqian-${index}`],
      ruleIds: [`place-${starName}`],
      status: "verified",
      purpose: `依太歲十二神順序安${starName}。`,
      narration: ["歲建晦氣喪門起，貫索官符小耗比，大耗龍德白虎神，天德弔客病符止。"],
      commonMistakes: ["歲前十二神的同名星需看 category，不可與博士十二神或年支神煞混用。"]
    })),
    ...[
      "將星", "攀鞍", "歲驛", "息神", "華蓋", "劫煞", "災煞", "天煞", "指背", "咸池", "月煞", "亡神"
    ].map((starName, index) => ({
      id: `place-jiangqian-${index + 1}`,
      order: 96 + index,
      title: `安${starName}`,
      shortTitle: starName,
      type: "reference-table",
      prerequisiteStepIds: [index === 0 ? "place-suiqian-12" : `place-jiangqian-${index}`],
      ruleIds: [`place-${starName}`],
      status: "verified",
      purpose: `依將前諸星順序安${starName}。`,
      narration: ["將星三合起旺地，攀鞍歲驛息神方，華蓋劫災天三煞，指背咸池月煞亡。"],
      commonMistakes: ["將前十二神以三合旺地起將星，不是直接由年支起將星。"]
    }))
  ]
};
